#!/usr/bin/php
<?php   
/*----------------------------------------------------------------------------*/
// Copyright (C) 2009  Paul Yasi (citrusdb.org)
// This script will email a receipt to customers who have the automatic receipt
// field marked Yes in their billing record
//
// This script should be put into the cron to be run nightly
//
/*----------------------------------------------------------------------------*/

$from_email = "yourname@example.com";


// Includes
include('./include/config.inc.php');
include('./include/database.inc.php');
include('./include/billing.inc.php');
include('./include/citrus_base.php');
include('./include/support.inc.php');


// Select them from the database
$query = "SELECT b.id b_id, b.contact_email, b.name, b.company, ".
  "b.account_number, ph.id ph_id, ph.billing_amount, ph.creation_date ".
  "FROM billing b ".
  "LEFT JOIN customer c on c.account_number = b.account_number ".
  "LEFT JOIN payment_history ph ON ph.billing_id = b.id ".
  "WHERE b.automatic_receipt = 'y' AND ph.creation_date = CURRENT_DATE";

$DB->SetFetchMode(ADODB_FETCH_ASSOC);
$receiptresult = $DB->Execute($query) or die ("automatic_receipt select for today failed");

while ($myreceiptresult = $receiptresult->FetchRow()) {
  $paymentid = $myreceiptresult['ph_id'];
  $amount = $myreceipttresult['billing_amount'];
  $billingid = $myreceiptresult['b_id'];
  $payment_date = $myreceiptresult['creation_date'];
  
  /*-------------------------------------------------------------------------*/
  // print paid_amounts from billing_details
  /*-------------------------------------------------------------------------*/
  
  $query = "SELECT * FROM billing b ".
    "LEFT JOIN general g ON g.id = b.organization_id ".
    "WHERE b.id = $billingid";
  $DB->SetFetchMode(ADODB_FETCH_ASSOC);
  $result = $DB->Execute($query) or die ("billing table Query Failed");
  $myresult = $result->fields;
  $billing_name = $myresult['name'];
  $billing_company = $myresult['company'];
  $billing_street = $myresult['street'];
  $billing_city = $myresult['city'];
  $billing_state = $myresult['state'];
  $billing_zip = $myresult['zip'];
  $billing_account_number = $myresult['account_number'];
  $org_name = $myresult['org_name'];
  
  echo "<h2>$org_name</h2>".
    "<h3>$l_paymentreceipt</h3>".
    "$l_accountnumber: $billing_account_number<br><br>\n\n".
    "$billing_name<br>".
    "$billing_company<br>".
    "$billing_street<br>".
    "$billing_city $billing_state $billing_zip<p>";
  
  $human_date = humandate($payment_date, $lang);
  
  echo "$l_paid: $amount on $human_date for:<p>";
  
  
  // get the resulting list of services that have payment applied with
  // the matching payment_history_id
  //$DB->debug = true;
  
  $query = "SELECT bd.original_invoice_number, bd.paid_amount,".
    "bd.billed_amount, ms.service_description, tr.description FROM ".
    "billing_details bd ".
    "LEFT JOIN user_services us ON us.id = bd.user_services_id ".
    "LEFT JOIN master_services ms ON ms.id = us.master_service_id ".
    "LEFT JOIN taxed_services ts ON ts.id = bd.taxed_services_id ".
    "LEFT JOIN tax_rates tr ON tr.id = ts.tax_rate_id ".
    "WHERE bd.payment_history_id = '$paymentid' ORDER BY bd.taxed_services_id";
  $DB->SetFetchMode(ADODB_FETCH_ASSOC);
  $result = $DB->Execute($query) or die ("Receipt Query Failed");
  
  echo "<table>";
  echo "<td>$l_invoice</td><td>$l_description</td><td>$l_paid</td><td>$l_stillowed</td><tr>";
  
  while ($myresult = $result->FetchRow()) {
    $invoice = $myresult['original_invoice_number'];
    $description = $myresult['service_description'];
    $tax_description = $myresult['description'];
    $paid_amount = sprintf("%.2f",$myresult['paid_amount']);
    $billed_amount = sprintf("%.2f",$myresult['billed_amount']);  
    
    $owed_amount = sprintf("%.2f",$billed_amount - $paid_amount);
    
    if ($tax_description) {
      // print the tax as description instead
      echo "<td>$invoice</td><td>&nbsp;&nbsp;&nbsp;$tax_description</td><td>$paid_amount</td><td>$owed_amount</td><tr>";
    } else {
      echo "<td>$invoice</td><td>$description</td><td>$paid_amount</td><td>$owed_amount</td><tr>";
    }
  }
  echo "</table>";

 } // end while myreceipt result

?>
